### ISSUE TITLE
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL 

### ISSUE THREAD

**Issue by TobiGoldD** [elizaOS/eliza#2127]
**Describe the bug**
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @elizaos/agent@0.1.7 start: `node --loader ts-node/esm src/index.ts "--isRoot"`
Exit status 1

**Comment by TobiGoldD** [comment]
![image](https://github.com/user-attachments/assets/c78b1810-39f0-47f4-8f42-54ee9fa31826)
![ai issue](https://github.com/user-attachments/assets/1dd763b3-497e-4860-a6f0-5ebe90c1b3b4)

**Comment by brij2001-hof** [comment]
Are you trying to run in windows environment? 
Error might or might not be related to the windows environment but if are on Windows, you will need WSL anyway, try to run it in that.

**Comment by leyr1112** [comment]
What is error, please share screenshot here

**Comment by TobiGoldD** [comment]
![image](https://github.com/user-attachments/assets/fe0064c7-ca0f-4c92-891a-2ec8a6ded428)

**Comment by leyr1112** [comment]
in agent folder, you can run pnpm start

**Comment by TobiGoldD** [comment]
that is the error that comes up when i run pnpm start or npm start

**Comment by TobiGoldD** [comment]
![image](https://github.com/user-attachments/assets/090a6961-aff0-4739-9f23-33c1281db993)

**Comment by TobiGoldD** [comment]
![image](https://github.com/user-attachments/assets/f6bde072-8b58-49d7-8d8a-97d09c99ee5b)

**Comment by xLuisCumbi** [comment]
Same problem in MacOS

**Comment by aijustinmoon** [comment]
Same problem here.

**Comment by AIFlowML** [comment]
I run on Apple Silicon with no issues.
Can you all try run the ElizaOS not the starter (in case it was the starter) and send me a feedback please ?

**Comment by gedithejedi** [comment]
Downgrade your node to exactly `23.3.0` and follow the docs to do a fresh setup.

**Comment by rustyralminar** [comment]
hi are you already fix this error? i have same problem

**Comment by leyr1112** [comment]
sudo apt-get install build-essential
run this command on linux

**Comment by 0x3N3jVhPUV** [comment]
I have the sama issue :/
Did someone find a solution?

**Comment by xLuisCumbi** [comment]
> I have the sama issue :/
> Did someone find a solution?

Yes 
Try to checkout the last release
Has been solved on the last one

**Comment by purpleethereum** [comment]
I've had the same issue on macOS. Checking out on latest release alone didn't solve my issue, because i was adding API_KEY only in defaultCharacter.ts; These are the steps i've gone through:
Clone Eliza repo -> Make sure you use node v23.3.0 -> Checkout to latest release -> Copy .env-example into .env -> Make sure you have API_KEY in your env and change the modelProvider if you need to -> pnpm i && pnpm build && pnpm start

Not sure if node v23.3.0 is essential, but it throws out warning unless you use it.

**Comment by zubyoha** [comment]
I have the same issue, did anyone find a solution to the issue?

**Comment by sparkidea25** [comment]
> I have the same issue, did anyone find a solution to the issue?

@purpleethereum solutions seems to work @zubyoha
