### ISSUE TITLE
getRecentPostInteractions returning all memory

### ISSUE THREAD

**Issue by rferrari** [elizaOS/eliza#2253]
**Is your feature request related to a problem? Please describe.**

I`m not sure if this is a BUG or intent, but looks like runtime.ts getRecentPostInteractions return all memory. It was overloading my model with more than 20k tokens each time it try to create a new post.

So, it stopped creating new posts due Model Rate Limits per minute.

**Describe the solution you'd like**

A workarround i found so far, was to limit the getRecentPostInteractions with a setting like this:

```
const getRecentPostInteractions = async (
            recentInteractionsData: Memory[],
            actors: Actor[]
        ): Promise<string> => {
            const limit = this.character.settings?.recentInteractionsLimit ?? 20;  // Included limit here
            const limitedInteractions = recentInteractionsData.slice(-limit);
            const formattedInteractions = formatPosts({
                messages: recentInteractionsData,
                actors,
                conversationHeader: true,
            });

            return formattedInteractions;
        };
```

**Describe alternatives you've considered**

I`m not sure if is the best solution as i`m still learning Eliza Framework. Maybe a more experience dev can check on that.

**Additional context**

**Comment by augchan42** [comment]
In theory the recent interactions should already be limited to the 20 latest here:
```
const getRecentInteractions = async (
            userA: UUID,
            userB: UUID
        ): Promise<Memory[]> => {
            // Find all rooms where userA and userB are participants
            const rooms = await this.databaseAdapter.getRoomsForParticipants([
                userA,
                userB,
            ]);

            // Check the existing memories in the database
            const existingMemories =
                await this.messageManager.getMemoriesByRoomIds({
                    // filter out the current room id from rooms
                    roomIds: rooms.filter((room) => room !== roomId),
                });

            // Sort messages by timestamp in descending order
            existingMemories.sort(
                (a, b) =>
                    (b?.createdAt ?? Date.now()) - (a?.createdAt ?? Date.now())
            );

            // Take the most recent messages
            const recentInteractionsData = existingMemories.slice(0, 20);
            return recentInteractionsData;
        };
```

This is whats passed to getRecentPostInteractions.  So not sure why everything is getting passed.  I do remember seeing rate limits as well, but I also had other code changes so not sure if it's the same underlying issue.

**Comment by augchan42** [comment]
there's an inefficiency in memory retrieval, so will fix this issue at the same time

**Comment by augchan42** [comment]
@rferrari what database are you using?  it seems the limit parameter is being lost between layers, as the type definition has it, but the underlying database adapter doesn't.  At least for sqlite and likely many others.

**Comment by shakkernerd** [comment]
@rferrari YesThe limit implementation was missing in the sqlite adapter and #2264 should fix this.

**Comment by rferrari** [comment]
Nice, is the sqlite im using so far, but i want to migrate to supabase, but still not working

**Comment by augchan42** [comment]
Please open a new case and state the adapter/ connector /plugin you are
using.

**Comment by rferrari** [comment]
@augchan42 , hope to find you well!

about that supabase database issue:

https://github.com/elizaOS/eliza/issues/3160
