### ISSUE TITLE
After running Pnpm start

### ISSUE THREAD

**Issue by SnoochiMink** [elizaOS/eliza#3151]
pnpm -v 10.0.0
nvm -v 0.40.1
node -v  v23.3.0                                                 

Installed all prerequisites and dependencies correctly

'pnpm install --no-frozen-lockfile'

got this after install: 
  
![Image](https://github.com/user-attachments/assets/acb75e9f-9960-4ba4-bdaf-b0905cd3dae5)

decided to run build anyways

'pnpm build'

Ran pnpm start and got this error:
![Image](https://github.com/user-attachments/assets/a2be968a-44a6-474b-9f17-1690919979da)

**Comment by tcm390** [comment]
Try pulling the latest code. This PR should fix it: https://github.com/elizaOS/eliza/pull/2901

**Comment by AbstractLogica** [comment]
I was having this issue the other day, I think it ended up being to do with the version of Node I was running
Try `nvm use 23.3` before building

**Comment by medardm** [comment]
Additionally, make sure to delete your node modules first then reinstall if still doesn't work.

> I was having this issue the other day, I think it ended up being to do with the version of Node I was running Try `nvm use 23.3` before building

**Comment by yasir23** [comment]
You can contact me there on my gig I will help you out!

https://www.fiverr.com/s/gDjxQeA

**Comment by AbstractLogica** [comment]
> You can contact me there on my gig I will help you out!

Imagine using a debugging forum of an open-source community-built project to charge people to fix their issues 💀
