### ISSUE TITLE
Failed to create Twitter client

### ISSUE THREAD

**Issue by tcm390** [elizaOS/eliza#4146]
<img width="812" alt="Image" src="https://github.com/user-attachments/assets/3aa6e12e-ec2a-41f4-b537-395cbba5699b" />

Steps to Reproduce:

1. Purge the database

2. Run the Twitter plugin

**Comment by wtfsayo** [comment]
I think I fixed it in https://github.com/elizaOS/eliza/pull/4151

**Comment by tcm390** [comment]
> I think I fixed it in [#4151](https://github.com/elizaOS/eliza/pull/4151)

hmmm....not really, still encountering it

<img width="812" alt="Image" src="https://github.com/user-attachments/assets/b9c68f04-b868-4f91-9490-2fdf9a1cbdb9" />

**Comment by tcm390** [comment]
The issue occurs because the service starts before the agent is created.
