### ISSUE TITLE
Web client thinks it is on a different version

### ISSUE THREAD

**Issue by scottrepreneur** [elizaOS/eliza#4924]
**Describe the bug**

The web client shows `v1.0.3` but the cli and core are on `v1.0.4`

**To Reproduce**

1. `elizaos create`
2. select defaults
3. cd & `elizaos start`
4. open web client
5. see incorrect version and update spaz banner

**Expected behavior**

Should see matching version in web client

**Screenshots**

<img width="232" alt="Image" src="https://github.com/user-attachments/assets/185ab37d-74c7-4c29-a6aa-2ec0afccc2fc" />

https://github.com/user-attachments/assets/c435654e-56df-4ecd-93f5-3faf2d1db91c

**Comment by ChristopherTrimboli** [comment]
looking at now

**Comment by standujar** [comment]
I think that is fixed, I can't reproduce

**Comment by scottrepreneur** [comment]
The repeated 429 error appears to be resolved around `v1.0.7/8`. As of `v1.0.11` I'm still seeing the different version issue, where the client thinks it's a version (at least) behind.

Currently, on `v1.0.11`, I'm seeing `1.0.10` in the web client. The client also requests an update. This instance was updated from `v1.0.7` to `v1.0.11` recently.

```json
    "@elizaos/cli": "1.0.11",
    "@elizaos/core": "^1.0.11",
```

**Comment by wtfsayo** [comment]
it was fixed
